### ISSUE TITLE
[Bug]: Batched Multi-LoRA inference failure with random length dataset

### ISSUE THREAD

**Issue by tae-su-kim** [HabanaAI/vllm-fork#237] opened 2024-09-04 08:45 UTC
### Anything you want to discuss about vllm.

Environment:
```
SynapseAI 1.17.0
vault.habana.ai/gaudi-docker/1.17.0/ubuntu22.04/habanalabs/pytorch-installer-2.3.1:latest
habana_main branch
```

Current implementation of batched multi-lora suffers from RuntimeError on online serving scenarios (e.g. OpenAI API). This bug can be reproduced with following script:

Server:
```
VLLM_SKIP_WARMUP=true python -m vllm.entrypoints.openai.api_server     --model /models/Meta-Llama-3-8B-Instruct     --block-size 128   --max-model-len 2048     --max-loras 2     --max-lora-rank 8     --enable-lora     --lora-modules lora-1=/models/Gaudi_LoRA_Llama-3-8B-Instruct lora-2=/models/Gaudi_LoRA_Llama-3-8B-Instruct
```

Send requests with any dataset and LoRA pattern to the API server with number of requests >= 8. Below is an example command line for our benchmark script (https://github.com/SqueezeBits/vllm-fork/tree/benchmark).
```
python benchmarks/benchmark_sqzb.py --tokenizer /models/Meta-Llama-3-8B-Instruct/ --dataset benchmarks/ShareGPT_V3_unfiltered_cleaned_split.json --max-input-len 1024 --max-output-len 8 --mimic-throughput-sample --lora-pattern ,lora-
1,lora-2 -n 16
```

Then, following error occurs:
```
(Abbreviated)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1544, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/codes/vllm/model_executor/models/llama.py", line 429, in forward
    model_output = self.model(input_ids, positions, kv_caches,
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1535, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1585, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/workspace/codes/vllm/model_executor/models/llama.py", line 314, in forward
    hidden_states = self.get_input_embeddings(input_ids)
  File "/workspace/codes/vllm/model_executor/models/llama.py", line 299, in get_input_embeddings
    return self.embed_tokens(input_ids)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1535, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1585, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/workspace/codes/vllm/lora/layers.py", line 330, in forward
    indices = self.embeddings_indices[1][:embedding_len].view_as(x)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

This error happens due to the number of tokens in a prefill batch being larger than max_num_batched_tokens. As discussed in PR #109 , current implementation of prefill scheduler may let a prefill batch to have the number of tokens exceeding max_num_batched tokens after padding. While, several indices information for LoRA in LoRAModelManager is designed to support only up to max_num_batched_tokens: https://github.com/HabanaAI/vllm-fork/blob/b4f6a295c3e663872a8dadb0caca0fd21995e105/vllm/lora/models.py#L425-L440
This causes L330 in vllm/lora/layer.py to fail on view_as(x).

Suggested solutions are either (1) to merge PR #109 or (2) increase the size of embeddings_indices and other indices to the maximum number of padded prefill tokens under max_num_batched_tokens constraint.

**Comment by vivekgoe** [comment] 2024-09-04 10:34
@tae-su-kim Please add --max-num-batched-tokens <value> to server command, where value >= max_num_seqs * max_seq_len.    E.g. for num_requests = 16 and max-input-len 1024,  value >= 16384.  With this additional parameter added to server command I was able to execute commands you shared without errors.

For testing larger batch-sizes > 32 or 64 you will run into OOM issues. Please use https://github.com/HabanaAI/vllm-fork/pull/223 which has optimizations to enable executing with larger batch-sizes.

**Comment by tae-su-kim** [comment] 2024-09-04 10:47
@vivekgoe Thanks for the fast response.
Setting max_num_batched_tokens >= max_num_seqs * max_seq_len can indeed prevent the padding issue, but will cause significant effective prefill throughput degradation in certain cases. e.g., consider 256 prefills with length [128, 128, ..., 128, 128, 2048] batched at the same time. This batch will become [2048, 2048, ..., 2048, 2048] after padding.
If the design choice is to rather keep the scheduler intact, I think max_num_batched_tokens >= max_num_seqs * max_seq_len must be included as an assertion when enable_lora is True (at least).

I will definitely check #223 for further benchmarks. Thanks for the lookahead!

**Comment by vivekgoe** [comment] 2024-09-04 10:53
@tae-su-kim Adding assertion to check max_num_batched_tokens >= max_num_seqs * max_seq_len for enable_lora = True is a good suggestion, will add it.  Regarding possibility of change in scheduler to handle this better, we will discuss this and get back.

**Comment by vivekgoe** [comment] 2024-09-11 13:51
@JHLEE17 Please share the commit which you used for above. Will check and get back.

**Comment by JHLEE17** [comment] 2024-09-11 15:04
> @JHLEE17 Please share the commit which you used for above. Will check and get back.

@vivekgoe Oh, I missed it. I'm currently working with commit '53f96b7'.

**Comment by SanjuCSudhakaran** [comment] 2024-09-13 11:14
Cases 1 and 2 [batch size 128]:  Device out-of-memory issue is observed with enforce-eager flag and warmup enabled. We have reported the issue internally and started looking into it with priority.

If enforce-eager flag is removed and warmup-run  is enabled, the test runs without any issues. You could continue your experiments with this configuration.

case 3 [batch size 256]: For higher batch size like 256. we have also  observed device out-of -memory issue and the debug is in progress.

Note: To get better performance, set max-num-batched-tokens to max_num_seqs * max-model-len

Command used to run server is shared here. vllm-fork head f858d435
```
python -m vllm.entrypoints.openai.api_server \
    --model /scratch-1/models/Meta-Llama-3.1-8B-Instruct  \
    --block-size 128 \
    --max-model-len 2048 \
    --enable-lora \
    --max-loras 2 \
    --max-lora-rank 8 \
    --lora-modules lora-1=/scratch-1/models/Gaudi_LoRA_Llama-3-8B-Instruct lora-2=/scratch-1/models/Gaudi_LoRA_Llama-3-8B-Instruct \
    --max-num-seqs 128 \
    --max-num-batched-tokens 262144 #max-num-seqs * max-model-len```

**Comment by SanjuCSudhakaran** [comment] 2024-09-17 11:48
For case 1 and 2, profile-run was under-estimating the expected memory usage. Setting VLLM_PROMPT_BS_BUCKET_MAX to 128 will fix the OOM issue.

Command used to run server in without HPUGraphs is shared below. vllm-fork head 4c1ca3a0

```
VLLM_SKIP_WARMUP=true \
VLLM_PROMPT_BS_BUCKET_MAX=128 \
python -m vllm.entrypoints.openai.api_server \
    --model /scratch-1/models/Meta-Llama-3.1-8B-Instruct  \
    --block-size 128 \
    --max-model-len 2048 \
    --enforce-eager \
    --enable-lora \
    --max-loras 2 \
    --max-lora-rank 8 \
    --lora-modules lora-1=/scratch-1/models/Gaudi_LoRA_Llama-3-8B-Instruct lora-2=/scratch-1/models/Gaudi_LoRA_Llama-3-8B-Instruct \
    --max-num-seqs 128 \
    --max-num-batched-tokens 262144 #max-num-seqs * max-model-len```
```

**Comment by JHLEE17** [comment] 2024-09-19 06:36
I’ve successfully tested with `--max-input-len 1024` (`--max-model-len 2048`), and confirmed that it works well not only when `VLLM_PROMPT_BS_BUCKET_MAX` and `--man-num-seqs` are set to `128`, but also when both are set to `256`. Thanks for your help! However, when I increase `--max-input-len` to `2048` (`--max-model-len 3072`) and the number of requests exceeds 128, I encounter an error that seems to be OOM-related, similar to what I reported earlier. It seems there may be a memory management issue when using Multi-LoRA. Is there a potential fix for this issue?

You can reproduce the results with these commands.
Server:
```
VLLM_SKIP_WARMUP=true \
VLLM_PROMPT_BS_BUCKET_MAX=128 \
python -m vllm.entrypoints.openai.api_server \
    --model /scratch-1/models/Meta-Llama-3.1-8B-Instruct  \
    --block-size 128 \
    --max-model-len 3072 \
    --enforce-eager \
    --enable-lora \
    --max-loras 2 \
    --max-lora-rank 8 \
    --lora-modules lora-1=/scratch-1/models/Gaudi_LoRA_Llama-3-8B-Instruct lora-2=/scratch-1/models/Gaudi_LoRA_Llama-3-8B-Instruct \
    --max-num-seqs 128 \
    --max-num-batched-tokens 393216  #max-num-seqs * max-model-len
```

Client:
```
python benchmarks/benchmark_sqzb.py     \
--tokenizer /scratch-1/models/Meta-Llama-3.1-8B-Instruct     \
--dataset /scratch-1/datasets/dynamic_sonnet_llama3/dynamic_sonnet_llama_3_prefix_512_max_2048_1024_sampled.parquet     \
--max-input-len 2048     \
--max-output-len 1024     \  # or 1
--lora-pattern ,lora-1,lora-2    \
-n 1024
```

**Comment by SanjuCSudhakaran** [comment] 2024-09-19 15:04
I could reproduce the device OOM issue locally with the given configuration.

The same issue is observed without LoRA also and the related debug is in progress.

**Closed** 2024-09-27 06:58 UTC
Labels: bug
